package com.preston.data.repo.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.preston.data.repo.greendao.User;
import com.preston.data.repo.greendao.Stock;

import com.preston.data.repo.greendao.UserDao;
import com.preston.data.repo.greendao.StockDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig stockDaoConfig;

    private final UserDao userDao;
    private final StockDao stockDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        stockDaoConfig = daoConfigMap.get(StockDao.class).clone();
        stockDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        stockDao = new StockDao(stockDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(Stock.class, stockDao);
    }
    
    public void clear() {
        userDaoConfig.clearIdentityScope();
        stockDaoConfig.clearIdentityScope();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public StockDao getStockDao() {
        return stockDao;
    }

}
