package com.preston.data.repo.greendao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.
/**
 * Entity mapped to table "USER".
 */
@Entity
public class User {
    private String encodedId;
    private String name;

    @Generated
    public User() {
    }

    @Generated
    public User(String encodedId, String name) {
        this.encodedId = encodedId;
        this.name = name;
    }

    public String getEncodedId() {
        return encodedId;
    }

    public void setEncodedId(String encodedId) {
        this.encodedId = encodedId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
