package com.preston.data.repo.greendao.stock;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.preston.data.repo.greendao.stock.StockEntity;

import com.preston.data.repo.greendao.stock.StockEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig stockEntityDaoConfig;

    private final StockEntityDao stockEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        stockEntityDaoConfig = daoConfigMap.get(StockEntityDao.class).clone();
        stockEntityDaoConfig.initIdentityScope(type);

        stockEntityDao = new StockEntityDao(stockEntityDaoConfig, this);

        registerDao(StockEntity.class, stockEntityDao);
    }
    
    public void clear() {
        stockEntityDaoConfig.clearIdentityScope();
    }

    public StockEntityDao getStockEntityDao() {
        return stockEntityDao;
    }

}
