package com.preston.data.repo.greendao.stock;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.
/**
 * Entity mapped to table "STOCK".
 */
@Entity
public class Stock {

    @Id
    @NotNull
    @Unique
    @Index
    private String ticker;
    private Long dailyVolume;
    private Double change;
    private Double daysLow;
    private Double daysHigh;
    private Double yearsLow;
    private Double yearsHigh;
    private String marketCapitalization;
    private Double lastTradePrice;
    private String daysRange;
    private String name;
    private Long volume;
    private String stockExchange;

    @Generated
    public Stock() {
    }

    public Stock(String ticker) {
        this.ticker = ticker;
    }

    @Generated
    public Stock(String ticker, Long dailyVolume, Double change, Double daysLow, Double daysHigh, Double yearsLow, Double yearsHigh, String marketCapitalization, Double lastTradePrice, String daysRange, String name, Long volume, String stockExchange) {
        this.ticker = ticker;
        this.dailyVolume = dailyVolume;
        this.change = change;
        this.daysLow = daysLow;
        this.daysHigh = daysHigh;
        this.yearsLow = yearsLow;
        this.yearsHigh = yearsHigh;
        this.marketCapitalization = marketCapitalization;
        this.lastTradePrice = lastTradePrice;
        this.daysRange = daysRange;
        this.name = name;
        this.volume = volume;
        this.stockExchange = stockExchange;
    }

    @NotNull
    public String getTicker() {
        return ticker;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTicker(@NotNull String ticker) {
        this.ticker = ticker;
    }

    public Long getDailyVolume() {
        return dailyVolume;
    }

    public void setDailyVolume(Long dailyVolume) {
        this.dailyVolume = dailyVolume;
    }

    public Double getChange() {
        return change;
    }

    public void setChange(Double change) {
        this.change = change;
    }

    public Double getDaysLow() {
        return daysLow;
    }

    public void setDaysLow(Double daysLow) {
        this.daysLow = daysLow;
    }

    public Double getDaysHigh() {
        return daysHigh;
    }

    public void setDaysHigh(Double daysHigh) {
        this.daysHigh = daysHigh;
    }

    public Double getYearsLow() {
        return yearsLow;
    }

    public void setYearsLow(Double yearsLow) {
        this.yearsLow = yearsLow;
    }

    public Double getYearsHigh() {
        return yearsHigh;
    }

    public void setYearsHigh(Double yearsHigh) {
        this.yearsHigh = yearsHigh;
    }

    public String getMarketCapitalization() {
        return marketCapitalization;
    }

    public void setMarketCapitalization(String marketCapitalization) {
        this.marketCapitalization = marketCapitalization;
    }

    public Double getLastTradePrice() {
        return lastTradePrice;
    }

    public void setLastTradePrice(Double lastTradePrice) {
        this.lastTradePrice = lastTradePrice;
    }

    public String getDaysRange() {
        return daysRange;
    }

    public void setDaysRange(String daysRange) {
        this.daysRange = daysRange;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Long getVolume() {
        return volume;
    }

    public void setVolume(Long volume) {
        this.volume = volume;
    }

    public String getStockExchange() {
        return stockExchange;
    }

    public void setStockExchange(String stockExchange) {
        this.stockExchange = stockExchange;
    }

}
